
version: '3.8'

services:
  vuejs:
    build: .
    container_name: vuejs-container
    volumes:
      - ./src:/app
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./src:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - vuejs

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
